import "../globals.css";
import MainHeader from "@/components/MainHeader/MainHeader";

export const metadata = {
  title: "UFC NEWS",
  description: "Generated by Almayo Mekonen",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div id="page">
          <MainHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
