import "../globals.css";

export const metadata = {
  title: "UFC NEWS UPDATES",
  description: "Generated by Almayo Mekonen",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/ufc.png" type="image/x-icon" />
      </head>
      <body>
        <div id="page">{children}</div>
      </body>
    </html>
  );
}
